version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: sgmb/yatube:latest
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    depends_on:
      - web
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./favicon.ico:/var/html/favicon.ico
      - /etc/nginx/ssl/:/etc/nginx/ssl/
      - static_value:/var/html/static/
      - media_volume:/var/html/media/

volumes:
  static_value:
  media_volume:
